### ISSUE TITLE
Connect Sign-in function to Login UI

### ISSUE THREAD

**Issue by JerryEsperanza** [RenardMacorol/NEU-OJT-APP#5]

**Comment by RenardMacorol** [comment]
# Log-in button with functionality
![Image](https://github.com/user-attachments/assets/c254dd1a-5e19-4927-8e08-fc7a5dae3b92)

### Not Neu Email Login
![Image](https://github.com/user-attachments/assets/016c2492-7abb-4497-a04c-03f207a85fb2)

### Neu Login 
![Image](https://github.com/user-attachments/assets/56ee8e88-6b1b-427b-9ebf-320508006446)
